const char APN[] = "internet";
const char *ssid = "plantWifi";
const char *password = "987654321";

char str[215];
String apikeyVal = "go123";

bool rtcStatus = true;
bool bmpStatus = false;
bool spiffsStatus = true;
bool runStatus = false;
bool serialStatus = true;
bool simStatus = false;

int sw1Pin = 12;
int sw2Pin = 4;
int sw3Pin = 2;
int rainPin = 34;
int windPin = 35;
int simTXPin = 16;
int simRXPin = 17;
int simRSTPin = 15;
int alarmPin = 27;
int buzzPin = 25;
int wdtPin = 32;
int csPin = 5;
int intPin = 27;
int ultrasonicT1Pin = 26;
int ultrasonicE1Pin = 33;
int ultrasonicT2Pin = 14;
int ultrasonicE2Pin = 13;

String C00 = "&C0=";
String C01 = "&C1=";
String C02 = "&C2=";
String C03 = "&C3=";
String C04 = "&C4=";
String C05 = "&C5=";
String C06 = "&C6=";
String C07 = "&C7=";
String C08 = "&C8=";
String C09 = "&C9=";
String C10 = "&C10=";
String C11 = "&C11=";
String C12 = "&C12=";
String C13 = "&C13=";
String C14 = "&C14=";

int serialVal;
int adcVal;
int apiVal;
int batCalibVal;
int sendTimeVal;
int sendTimeVals;
int ultrasonicGroundAVal;
int ultrasonicGroundBVal;
int sendCountVal;
int rainTotalVal;
int windSpeedTotalVal;
int rainVal;
int windSpeedVal;
int windDirectionVal;
int ultrasonicAVal;
int ultrasonicBVal;
int waterLevelAVal;
int waterLevelBVal;

float fbatCalibVal;
float fbatteryVal;
float firradianceVal;
float fairpressureVal;
float ftemperatureBmpVal;
float ftemperatureRtcVal;
float ftemperatureHdcVal;
float fhumidityHdcVal;

String sapiVal;
String sdatenowVal;
String stimenowVal;
String sunixnowVal;
String srainTotalVal;
String swindSpeedTotalVal;
String sbatCalibVal;
String ssendCountVal;
String sbatteryVal;
String sirradianceVal;
String sairpressureVal;
String stemperatureBmpVal;
String stemperatureRtcVal;
String stemperatureHdcVal;
String shumidityHdcVal;
String srainVal;
String swindSpeedVal;
String swindDirectionVal;
String sultrasonicAVal;
String swaterLevelAVal;
String sultrasonicBVal;
String swaterLevelBVal;
String sultrasonicGroundAVal;
String sultrasonicGroundBVal;
